backend:
  name: git-gateway
  branch: main # Change to your branch name if different

media_folder: "assets/img/uploads" # Folder where user uploaded files should go
public_folder: "assets/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "page.title", widget: "string" }
          - { label: "Email", name: "contact.email", widget: "string" }
          - { label: "Phone", name: "contact.phone", widget: "string" }
          - { label: "Site Name", name: "site.name", widget: "string" }
          - label: "Social Links"
            name: "social.links"
            widget: "list"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string" }
              - { label: "Instagram", name: "instagram", widget: "string" }
              - { label: "LinkedIn", name: "linkedin", widget: "string" }
          - { label: "Hero Title", name: "hero.title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero.subtitle", widget: "string" }
          - { label: "Hero Description", name: "hero.description", widget: "text" }
          - { label: "Hero Button 1", name: "hero.button1", widget: "string" }
          - { label: "Hero Button 2", name: "hero.button2", widget: "string" }
